# Fredit: A fresh editor.
#
# Copyright (C) 2009 Diwaker Gupta <diwaker@floatingsun.net>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301, USA.

def build(bld):
  libfred = bld.new_task_gen(
    features=["qt4", "cxx", "cstaticlib"],
    uselib = ["GFLAGS", "GLOG", "LUA", "QTCORE"],
    target = "fred",
    includes = [".."])

  libfred.source = [
    "buffer.cc",
    "cursor.cc",
    "font.cc",
    "fredit.cc",
    "line.cc",
    "registers.cc",
    "session.cc",
    "view.cc",
    "view-cursor.cc"
    ]

  libfred_test = bld.new_task_gen(
    features = ["cxx", "cprogram"],
    uselib = ["GFLAGS", "GLOG", "GTEST", "LUA", "QTCORE"],
    uselib_local = "fred",
    target = "libfred-tests",
    includes = [".."])
  libfred_test.source = [
    "cursor-test.cc",
    "main-test.cc"
    ]
