# Fredit: A fresh editor.
#
# Copyright (C) 2009 Diwaker Gupta <diwaker@floatingsun.net>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301, USA.

def set_options(ctx):
  ctx.tool_options('qt4')
  ctx.tool_options('compiler_cxx')

def configure(ctx):
  ctx.check_tool('compiler_cxx')
  ctx.check_tool('qt4')
  ctx.env.append_value('CXXFLAGS', '-g -DQT_CORE_LIB -DQT_SHARED'.split())

  # Configuration for google-glog.
  ctx.env.LIB_GLOG = 'glog'
  ctx.env.LIBPATH_GLOG = '/usr/lib'
  ctx.env.CPPPATH_GLOG = '/usr/include'

  # Configuration for google-gflags.
  ctx.env.LIB_GFLAGS = 'gflags'
  ctx.env.LIBPATH_GFLAGS = '/usr/lib'
  ctx.env.CPPPATH_GFLAGS = '/usr/include'

  # Configuration for googletest
  ctx.env.LIB_GTEST = 'gtest'
  ctx.env.LIBPATH_GTEST = '/usr/lib'
  ctx.env.CPPPATH_GTEST = '/usr/include'

  # Configuration for Lua.
  ctx.check_cfg(package = 'lua5.1', args = '--cflags --libs',
                uselib_store = 'LUA')

  ctx.recurse('core nfred')

def build(ctx):
  ctx.recurse('core core_runner nfred')
