# Fredit: A fresh editor.
#
# Copyright (C) 2009 Diwaker Gupta <diwaker@floatingsun.net>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA 02110-1301, USA.

def set_options(opt):
  opt.tool_options("qt4")

def configure(conf):
  conf.check_tool("g++")
  conf.check_tool("qt4")
  conf.env.append_value("CXXFLAGS", "-g -DQT_CORE_LIB -DQT_SHARED".split())

  # Configuration for google-glog.
  conf.env.LIB_GLOG = "glog"
  conf.env.LIBPATH_GLOG = "/usr/lib"
  conf.env.CPPPATH_GLOG = "/usr/include"

  # Configuration for google-gflags.
  conf.env.LIB_GFLAGS = "gflags"
  conf.env.LIBPATH_GFLAGS = "/usr/lib"
  conf.env.CPPPATH_GFLAGS = "/usr/include"

  # Configuration for googletest
  conf.env.LIB_GTEST = "gtest"
  conf.env.LIBPATH_GTEST = "/usr/lib"
  conf.env.CPPPATH_GTEST = "/usr/include"

  # Configuration for Lua.
  conf.env.LIB_LUA = "lua5.1"
  conf.env.LIBPATH_LUA = "/usr/lib"
  conf.env.CPPPATH_LUA = "/usr/include/lua5.1"

  # Configuration for libxdg-basedir
  conf.env.LIB_XDG_BASEDIR = "xdg-basedir"
  conf.env.LIBPATH_XDG_BASEDIR = "/usr/lib"
  conf.env.CPPPATH_XDG_BASEDIR = "/usr/include"

def build(bld):
  bld.add_subdirs("core core-runner nfred")
